# Setup
title:               Datu Adiatma
tagline:             'geologist'
description:         'I am a geologist, who is losing sleeps over things that happened in the past 4.5 billion years'
url:                 https://www.adtma.pw
baseurl:             ''
paginate:            5
paginate_path:       'blog/page:num'
permalink:           pretty

# About/contact
author:
  name:              Datu Adiatma
  url:               https://twitter.com/mas_datu
  email:             me@adtma.pw

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

excerpt_separator: <!--more-->
# Custom vars
version:             1.1.0
google_analytics_id: G-ZK5CBLPKVZ
